# Generated by Django 4.2.16 on 2024-11-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_author_alter_listing_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='experience_needed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='for_age_group',
            field=models.CharField(blank=True, choices=[('U5 - U6', 'U5 - U6'), ('U7 - U8', 'U7 - U8'), ('U9 - U10', 'U9 - U10'), ('U11 - U12', 'U11 - U12'), ('U13 - U14', 'U13 - U14'), ('U15 - U16', 'U15 - U16'), ('U16 - U19', 'U16 - U19'), ('Мъже', 'Мъже')], max_length=30, null=True),
        ),
    ]
