# Generated by Django 4.2.16 on 2024-11-12 09:14

import coach_app.listings.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_position_alter_listing_experience_needed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='licence_required',
            field=models.CharField(choices=[('Uefa PRO', 'Uefa PRO'), ('Uefa A', 'Uefa A'), ('Uefa B', 'Uefa B'), ('Uefa C', 'Uefa C'), ('National C', 'National C'), ('Grassroots D', 'Grassroots D'), ('Без лиценз', 'Без лиценз')], max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Заплатата трябва да бъде число по-голямо от 0')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='telephone_number',
            field=models.CharField(validators=[coach_app.listings.validators.TelephoneValidator()]),
        ),
    ]
