# Generated by Django 4.2.16 on 2024-11-12 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_licence_required_alter_listing_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
