# Generated by Django 4.2.16 on 2024-11-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_created_on_listing_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='updated_on',
            new_name='updated_at',
        ),
    ]
