# Generated by Django 4.2.16 on 2024-11-25 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_created_on_listing_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Заплатата трябва да бъде празно поле или число по-голямо от 0')]),
        ),
    ]
