# Generated by Django 4.2.16 on 2024-12-08 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drills', '0006_merge_20241202_2320'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_drills', to='drills.drill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_drills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
