# Generated by Django 4.2.16 on 2024-11-12 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('for_age_group', models.CharField(blank=True, choices=[('U5 - U6', 'U5 - U6'), ('U7 - U8', 'U7 - U8'), ('U9 - U10', 'U9 - U10'), ('U11 - U12', 'U11 - U12'), ('U13 - U14', 'U13 - U14'), ('U15 - U16', 'U15 - U16'), ('U16 - U19', 'U16 - U19'), ('Мъже', 'Мъже')], max_length=30, null=True)),
                ('graphics', models.ImageField(blank=True, null=True, upload_to='drills')),
                ('name', models.CharField(max_length=50)),
                ('objectives', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('focus', models.CharField(choices=[('Удари', 'Удари'), ('Подаване', 'Подаване'), ('Дрибъл', 'Дрибъл'), ('Владение', 'Владение'), ('1 срещу 1', '1 срещу 1'), ('2 срещу 1', '2 срещу 1')], max_length=20)),
                ('dimensions', models.CharField()),
                ('series', models.CharField()),
                ('duration', models.CharField()),
                ('coaching_points', models.TextField(max_length=250)),
                ('progression', models.CharField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
