# Generated by Django 4.2.16 on 2024-11-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0003_drill_approved_alter_drill_coaching_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drill',
            options={'permissions': [('can_approve_drills', 'Can approve drills')]},
        ),
    ]
