# Generated by Django 4.2.16 on 2024-11-28 17:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0004_alter_drill_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='graphics',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
