# Generated by Django 4.2.16 on 2024-12-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0005_alter_drill_created_at_alter_drill_updated_at'),
        ('drills', '0005_alter_drill_graphics'),
    ]

    operations = [
    ]
