# Generated by Django 4.2.16 on 2024-11-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='club',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
